MODEL:
  META_ARCHITECTURE: "SEC"
  BACKBONE:
    NAME: "build_vgg16_backbone"
  SEM_SEG_HEAD:
    NAME: "DeepLabLargeFOVHead"
    IN_FEATURES: ["conv5", ]
    NUM_CLASSES: 20
    IGNORE_VALUE: 255
    CONVS_DIM: 1024
    COMMON_STRIDE: 2
    NORM: "GN"
DATASETS:
  TRAIN: ('ws_voc_2012_train',)
  TEST: ('ws_voc_2012_val',)
SOLVER:
  IMS_PER_BATCH: 30
  BASE_LR: 0.002
  STEPS: (10000, 20000, 30000)
  MAX_ITER: 40000
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 4000
INPUT:
  MIN_SIZE_TRAIN: (480, 576, 688, 864, 1200)
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 864
  MAX_SIZE_TEST: 2000
TEST:
  EVAL_PERIOD: 4000
OUTPUT_DIR : "./output/v1"
