_BASE_: "./Base-SEC.yaml"
MODEL:
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  # PIXEL_STD: [57.375, 57.120, 58.395]
  BACKBONE:
    NAME: "build_vgg16_backbone"
#  WEIGHTS: "/home/ybt/meta-ws/output/models/vgg_new.pth"
#  VGG:
#    # OUT_FEATURES: ["conv5", ]
#    FREEZE_AT: 2
