_BASE_: "./Base-SEC.yaml"
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  BACKBONE:
    NAME: "build_deeplab_vgg16_backbone"
  WEIGHTS: "./output/models/vgg_new.pth"
INPUT:
  FORMAT: "RGB"
VIS_PERIOD: 0

#  VGG:
#    # OUT_FEATURES: ["conv5", ]
#    FREEZE_AT: 2
